# Generated by Django 4.1.1 on 2022-10-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='belonging_to_the_city',
        ),
        migrations.AddField(
            model_name='airport',
            name='belonging_to_the_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.city'),
        ),
    ]
