# Generated by Django 4.1.1 on 2022-10-29 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_airport_belonging_to_the_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_from', models.CharField(max_length=50)),
                ('where_to', models.CharField(max_length=50)),
                ('departure_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('price_for_an_adult', models.BigIntegerField()),
                ('price_for_an_child', models.BigIntegerField()),
                ('number_of_places_for_adults', models.BigIntegerField()),
                ('number_of_places_for_children', models.BigIntegerField()),
                ('type', models.CharField(choices=[('BB', 'bed & breakfast'), ('HB', ' half board'), ('FB', 'full board'), ('AI', 'all inclusive')], max_length=2, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='airport',
            name='belonging_to_the_city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='places.city'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='city',
            name='belonging_to_the_country',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='belonging_to_the_city',
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_adults', models.BigIntegerField()),
                ('amount_children', models.BigIntegerField()),
                ('unit_price_adult', models.BigIntegerField()),
                ('unit_price_child', models.BigIntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='places.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='belonging_to_the_country',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='places.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='belonging_to_the_city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='places.city'),
            preserve_default=False,
        ),
    ]
