# Generated by Django 4.1.1 on 2022-10-29 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0003_trip_alter_airport_belonging_to_the_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='places.trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='where_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_destination_trips', to='places.city'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='where_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_destination_trips', to='places.city'),
        ),
    ]
