# Generated by Django 4.1.1 on 2022-10-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_purchase_user_alter_purchase_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='type',
            field=models.CharField(choices=[('BB', 'bed & breakfast'), ('HB', ' half board'), ('FB', 'full board'), ('AI', 'all inclusive')], max_length=2),
        ),
    ]
