# Generated by Django 4.1.1 on 2022-11-05 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_trip_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='unit_price_adult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adult_price', to='places.trip'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='unit_price_child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_price', to='places.trip'),
        ),
    ]
