# Generated by Django 4.1.1 on 2022-11-06 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_remove_purchase_unit_price_adult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='airport',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='airport', to='places.airport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='places.hotel'),
            preserve_default=False,
        ),
    ]
