# Generated by Django 4.1.1 on 2022-11-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='points',
            field=models.IntegerField(default=1000),
        ),
    ]
